services:
  backend:
    build: ./backend
    container_name: network-map-backend
    network_mode: host
    privileged: true
    env_file: .env
    volumes:
      - ./datas:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: network-map-frontend
    network_mode: host
    restart: unless-stopped
